# Business Rules for Bank Churn Prediction
# Defines risk thresholds, retention budgets, and business logic

version: "1.0.0"
description: "Business rules and thresholds for churn prediction system"

churn_risk_thresholds:
  probability_ranges:
    low_risk:
      range: [0.0, 0.3]
      description: "Low churn probability"
      color: "green"
      action: "monitor"
      
    medium_risk:
      range: [0.3, 0.7]
      description: "Medium churn probability" 
      color: "yellow"
      action: "targeted_retention"
      
    high_risk:
      range: [0.7, 1.0]
      description: "High churn probability"
      color: "red"
      action: "aggressive_retention"
      
  binary_cutoff:
    threshold: 0.7
    description: "Probability threshold for binary churn risk classification"

retention_budgets:
  total_annual_budget: 5000000  # ₹50 lakhs
  budget_allocation:
    high_risk_customers:
      allocation_percentage: 60
      max_cost_per_customer: 5000  # ₹5,000
      retention_tactics: ["personal_relationship_manager", "fee_waivers", "premium_offers"]
      
    medium_risk_customers:
      allocation_percentage: 30  
      max_cost_per_customer: 2000  # ₹2,000
      retention_tactics: ["targeted_offers", "service_improvement", "product_recommendations"]
      
    low_risk_customers:
      allocation_percentage: 10
      max_cost_per_customer: 500   # ₹500
      retention_tactics: ["regular_communication", "satisfaction_surveys"]

driver_impact_scores:
  low_engagement:
    weight: 0.25
    critical_threshold: 0.6
    mitigation_actions: ["engagement_campaigns", "mobile_app_promotion", "transaction_alerts"]
    
  high_fees:
    weight: 0.20
    critical_threshold: 0.5
    mitigation_actions: ["fee_restructuring", "overdraft_protection", "penalty_waivers"]
    
  poor_service:
    weight: 0.15
    critical_threshold: 0.4
    mitigation_actions: ["service_quality_improvement", "complaint_resolution", "customer_feedback"]
    
  low_product_holding:
    weight: 0.10
    critical_threshold: 0.3
    mitigation_actions: ["cross_selling", "product_bundles", "loyalty_programs"]
    
  short_tenure:
    weight: 0.10
    critical_threshold: 0.3
    mitigation_actions: ["onboarding_programs", "relationship_building", "early_engagement"]
    
  credit_issues:
    weight: 0.10
    critical_threshold: 0.4
    mitigation_actions: ["credit_counseling", "debt_restructuring", "financial_planning"]
    
  balance_fluctuations:
    weight: 0.05
    critical_threshold: 0.5
    mitigation_actions: ["balance_alerts", "savings_products", "financial_education"]
    
  demographics:
    weight: 0.05
    critical_threshold: 0.6
    mitigation_actions: ["segmented_marketing", "personalized_communication"]

customer_segmentation:
  segments:
    premium_high_net_worth:
      criteria: ["income > 150000", "avg_account_balance > 100000"]
      priority: "highest"
      retention_budget_multiplier: 2.0
      
    digital_natives:
      criteria: ["age < 35", "digital_adoption > 0.8", "app_usage_minutes > 60"]
      priority: "high"
      retention_budget_multiplier: 1.5
      
    traditional_bankers:
      criteria: ["age > 55", "digital_adoption < 0.3"]
      priority: "medium"
      retention_budget_multiplier: 1.2
      
    new_customers:
      criteria: ["tenure_months < 6"]
      priority: "high"
      retention_budget_multiplier: 1.3
      
    struggling_customers:
      criteria: ["income < 30000", "credit_score < 600"]
      priority: "medium"
      retention_budget_multiplier: 1.0

model_performance_thresholds:
  classification_metrics:
    auc_roc:
      minimum: 0.75
      target: 0.85
      excellent: 0.90
      
    precision:
      minimum: 0.70
      target: 0.80
      excellent: 0.85
      
    recall:
      minimum: 0.65
      target: 0.75
      excellent: 0.80
      
    f1_score:
      minimum: 0.70
      target: 0.78
      excellent: 0.83
      
  business_metrics:
    capture_rate:
      minimum: 0.60
      target: 0.75
      excellent: 0.85
      
    false_positive_rate:
      maximum: 0.25
      target: 0.15
      excellent: 0.10

fairness_constraints:
  protected_attributes:
    - "age_group"
    - "income_bracket" 
    - "region"
    - "occupation_type"
    
  fairness_metrics:
    demographic_parity:
      threshold: 0.80
      description: "Prediction rate ratio between groups"
      
    equal_opportunity:
      threshold: 0.75
      description: "True positive rate ratio between groups"
      
    predictive_equality:
      threshold: 0.80
      description: "False positive rate ratio between groups"

alerting_rules:
  data_drift:
    feature_drift_threshold: 0.15
    target_drift_threshold: 0.10
    monitoring_frequency: "daily"
    
  model_performance:
    accuracy_drop_threshold: 0.05
    recall_drop_threshold: 0.08
    alert_frequency: "weekly"
    
  business_impact:
    churn_rate_increase_threshold: 0.03
    retention_cost_increase_threshold: 0.10
    review_frequency: "monthly"

compliance_rules:
  data_privacy:
    gdpr_compliance: true
    data_retention_period: 7  # years
    customer_consent_required: true
    
  regulatory_requirements:
    rbi_guidelines: true
    fair_lending_compliance: true
    transparency_requirements: true
    
  ethical_ai:
    bias_monitoring: true
    explainability_required: true
    human_oversight: true

roi_calculations:
  customer_lifetime_value:
    average_clv: 50000  # ₹50,000
    high_value_multiplier: 3.0
    low_value_multiplier: 0.5
    
  retention_cost_benefit:
    acceptable_cost_ratio: 0.3  # Max 30% of CLV
    target_retention_rate: 0.70
    break_even_retention_rate: 0.40
    
  intervention_effectiveness:
    high_risk_retention_rate: 0.25
    medium_risk_retention_rate: 0.15
    low_risk_retention_rate: 0.05

reporting_requirements:
  executive_dashboard:
    frequency: "weekly"
    metrics: ["churn_rate", "retention_rate", "model_performance", "roi"]
    
  operational_reports:
    frequency: "daily" 
    metrics: ["high_risk_customers", "intervention_status", "cost_tracking"]
    
  regulatory_reports:
    frequency: "quarterly"
    metrics: ["fairness_metrics", "compliance_status", "audit_trail"]