version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "timestamp: %(asctime)s, logger: %(name)s, level: %(levelname)s, message: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./logs/training.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_errors:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ./logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_inference:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ./logs/inference.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_drift:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: detailed
    filename: ./logs/data_drift.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  audit_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ./logs/audit_trail.csv
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  src:
    level: INFO
    handlers: [console, file_info]
    propagate: no

  src.synthetic_data_generator:
    level: INFO
    handlers: [console, file_info]
    propagate: no

  src.model_training:
    level: INFO
    handlers: [console, file_info]
    propagate: no

  src.inference:
    level: INFO
    handlers: [console, file_inference, audit_handler]
    propagate: no

  src.drift_detection:
    level: WARNING
    handlers: [console, file_drift]
    propagate: no

  src.validation:
    level: INFO
    handlers: [console, file_info]
    propagate: no

  ui:
    level: INFO
    handlers: [console, file_info]
    propagate: no

  tests:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, file_errors]